test commit
valorem-labs-inc/trade-interfaces pull request #13
Opened 2023-06-20 14:33 UTC by 0xAlcibiades

2023-06-22 01:00 UTC, dbelv requested changes

2023-06-22 01:00 UTC, dbelv commented on examples/rust/build.rs
> +        //.out_dir("src/google")  // you can change the generated code's location
I would just remove this comment since I don't think you would ever change the out_dir on the cargo build

2023-06-22 01:00 UTC, dbelv commented on examples/rust/examples/maker/maker.rs
> +    if fee % 3u64 == 0 && request_for_quote.action == i32::from(Action::Buy) && quote_zeroes {
This will never be true (since the fee is always set to 10) - I would just remove the ability to return a No Quote here.

2023-06-22 01:00 UTC, dbelv commented on examples/rust/examples/maker/maker.rs
> +    // We like what we see from the RFQ, construct the offer. We use magic for the price as it has
remove comment, it doesn't match the code

2023-06-22 01:00 UTC, dbelv commented on examples/rust/examples/maker/maker.rs
> +        // TODO Note: Issue 52 on Quay project.
I would remove this since Quay has moved and issues are being treated differently. It will just be addressed if/when it does

2023-06-22 01:00 UTC, dbelv commented on examples/rust/examples/maker/maker.rs
> +// Connect and setup a valid session within Quay
```suggestion
// Connect and setup a valid session
```

2023-06-22 01:00 UTC, dbelv commented on examples/rust/examples/maker/maker.rs
> +    // Connect and authenticate with Quay
```suggestion
```

2023-06-22 01:00 UTC, dbelv commented on examples/rust/examples/maker/maker.rs
> +    // Verify & authenticate with Quay before connecting to RFQ endpoint.
```suggestion
    // Verify & authenticate before connecting to the RFQ endpoint.
```

2023-06-22 01:00 UTC, dbelv commented on examples/rust/examples/maker/maker.rs
> +    // Verify the session with Quay
```suggestion
```

2023-06-22 01:00 UTC, dbelv commented on examples/rust/examples/maker/maker.rs
> +    println!("Maker has authenticated with Quay");
```suggestion
    println!("Maker has authenticated with Valorem");
```

2023-06-22 01:00 UTC, dbelv commented on examples/rust/examples/maker/maker.rs
> +// Approve the test tokens to used within the Arbitrum testnet
```suggestion
```

With the move of the token addresses to the settings this comment isn't really true anymore

2023-06-22 01:00 UTC, dbelv commented on examples/rust/examples/maker/maker.rs
> +    let gas_price = U256::from(5).mul(U256::exp10(8usize));
I would add a todo - we should ideally check the chain id and only apply this if the chain is a testnet. This is more for the future since this would be removed for mainnets.

2023-06-22 01:00 UTC, dbelv commented on examples/rust/examples/maker/maker.rs
> +        .expect("Unable to fetch Nonce from Quay");
```suggestion
        .expect("Unable to fetch Nonce from Valorem");
```

2023-06-22 01:00 UTC, dbelv commented on examples/rust/examples/maker/maker.rs
> +/// An example Market Maker (MM) client interface to Quay.
```suggestion
/// An example Market Maker (MM) interface to Valorem
```

2023-06-22 01:00 UTC, dbelv commented on examples/rust/examples/maker/maker.rs
> +/// The Market Maker will receive Request For Quote (RFQ) from the Quay server formatted as
```suggestion
/// The Market Maker will receive Request For Quote (RFQ) from the server formatted as
```

2023-06-22 01:00 UTC, dbelv commented on examples/rust/examples/maker/maker.rs
> +//     Move to step 2.
```suggestion
// Main execution function.
```
Given the logic changed around the hardcode line of no quotes, I would just remove this description altogether

2023-06-22 01:00 UTC, dbelv commented on examples/rust/examples/maker/maker.rs
> +    // Approve the tokens the example will be using on Arbitrum Testnet
```suggestion
    // Approve the tokens the example will be using
```

2023-06-22 01:00 UTC, dbelv commented on examples/rust/examples/maker/maker.rs
> +    // The stream to Quay might end for a couple of reasons, for example:
```suggestion
    // The gRPC stream might end for a couple of reasons, for example:
```

2023-06-22 01:00 UTC, dbelv commented on examples/rust/examples/maker/maker.rs
> +    // Every 3rd buy offer we send back a NoOffer response, otherwise its the price/fee of the offer
```suggestion
```

2023-06-22 01:00 UTC, dbelv commented on examples/rust/examples/maker/maker.rs
> +    // In order to sign the seaport order, we firstly transform the Quay OrderParameters
```suggestion
    // In order to sign the seaport order, we firstly transform the OrderParameters
```

2023-06-22 01:00 UTC, dbelv commented on examples/rust/examples/maker/maker.rs
> +            eprintln!("Unable to check authentication with Quay. Reported error:\n{error:?}");
```suggestion
            eprintln!("Unable to check authentication with Valorem. Reported error:\n{error:?}");
```

2023-06-22 01:00 UTC, dbelv commented on examples/rust/examples/maker/settings.rs
> +            .unwrap_or(String::from("exchange.valorem.xyz"));
While we are here, lets also update the default

```suggestion
            .unwrap_or(String::from("trade.valorem.xyz"));
```

2023-06-22 01:00 UTC, dbelv commented on examples/rust/examples/taker/settings.rs
> +            .unwrap_or(String::from("exchange.valorem.xyz"));
```suggestion
            .unwrap_or(String::from("trade.valorem.xyz"));
```

2023-06-22 01:00 UTC, dbelv commented on examples/rust/examples/taker/taker.rs
> +/// 1. Connect and authorise itself with Quay
```suggestion
/// 1. Connect and authorise itself with Valorem
```

2023-06-22 01:00 UTC, dbelv commented on examples/rust/examples/taker/taker.rs
> +    // Setup the stream between us and Quay which the gRPC connection will use.
```suggestion
    // Setup the stream between us and the server which the gRPC connection will use.
```

2023-06-22 01:00 UTC, dbelv commented on examples/rust/examples/taker/taker.rs
> +// Create and setup the connection to quay for use
```suggestion
// Create and setup the connection to Valorem
```

2023-06-22 01:00 UTC, dbelv commented on examples/rust/examples/taker/taker.rs
> +    // Connect and authenticate with Quay
```suggestion
```

2023-06-22 01:00 UTC, dbelv commented on examples/rust/examples/taker/taker.rs
> +        .expect("Unable to fetch Nonce from Quay");
```suggestion
        .expect("Unable to fetch Nonce");
```

2023-06-22 01:00 UTC, dbelv commented on examples/rust/examples/taker/taker.rs
> +    // Verify & authenticate with Quay before connecting to RFQ endpoint.
```suggestion
    // Verify & authenticate with the server before connecting to RFQ endpoint.
```

2023-06-22 01:00 UTC, dbelv commented on examples/rust/examples/taker/taker.rs
> +    // Verify the session with Quay
```suggestion
```

2023-06-22 01:00 UTC, dbelv commented on proto/valorem/trade/v1/auth.proto
> +package valorem.trade.v1;
Doesn't the path already imply this? How does the FE compile the proto given you have to provide a path for the build.rs I'm not sure if the change in package name really does anything

2023-06-22 03:22 UTC, dbelv approved these changes

2023-06-22 03:24 UTC, dbelv commented
Additional minor clean-up changes added. Added my approval to avoid issues with GH on merge however additional reviews required.

2023-06-22 03:33 UTC, merged

2023-06-23 19:56 UTC, 0xAlcibiades commented
@neodaoist cleaning up the branch. They can still see the delta with it gone.