clean up typescript examples
valorem-labs-inc/trade-interfaces pull request #14
Opened 2023-06-22 01:27 UTC by megsdevs

TODO handle RFQ service using Node stream

2023-06-22 07:30 UTC, dalechyn requested changes
Few ones

2023-06-22 07:30 UTC, dalechyn commented on docs/examples/typescript/src/RFQ_maker.ts
> +      let txReceipt = await (
Use const here

2023-06-22 07:30 UTC, dalechyn commented on docs/examples/typescript/src/RFQ_maker.ts
> +import ISeaport from '../../abi/ISeaport.json';
Move to top

2023-06-24 21:36 UTC, 0xAlcibiades requested changes
Feedback has been addressed.

2023-06-24 21:36 UTC, 0xAlcibiades commented on examples/typescript/gen/valorem/trade/v1/auth_connect.ts
> +  typeName: "quay.Auth",
trade.Auth

2023-06-24 21:36 UTC, 0xAlcibiades commented on examples/typescript/gen/valorem/trade/v1/auth_pb.ts
> +  static readonly typeName = "quay.NonceText";
trade

2023-06-24 21:36 UTC, 0xAlcibiades commented on examples/typescript/gen/valorem/trade/v1/auth_pb.ts
> +  static readonly typeName = "quay.VerifyText";
trade

2023-06-24 21:36 UTC, 0xAlcibiades commented on examples/typescript/gen/valorem/trade/v1/rfq_connect.ts
> +  typeName: "quay.RFQ",
trade

2023-06-24 21:36 UTC, 0xAlcibiades commented on examples/typescript/gen/valorem/trade/v1/rfq_pb.ts
> +proto3.util.setEnumType(Action, "quay.Action", [
trade

2023-06-24 21:36 UTC, 0xAlcibiades commented on examples/typescript/gen/valorem/trade/v1/types_pb.ts
> +  static readonly typeName = "quay.H96";
trade

2023-06-24 21:36 UTC, 0xAlcibiades commented on examples/typescript/gen/valorem/trade/v1/types_pb.ts
This generated file should not be in version control

2023-06-24 21:36 UTC, 0xAlcibiades commented on examples/typescript/gen/valorem/trade/v1/seaport_pb.ts
This generated file should not be in version control

2023-06-24 21:36 UTC, 0xAlcibiades commented on examples/typescript/gen/valorem/trade/v1/rfq_pb.ts
This generated file should not be in version control

2023-06-24 21:36 UTC, 0xAlcibiades commented on examples/typescript/gen/valorem/trade/v1/rfq_connect.ts
This generated file should not be in version control

2023-06-24 21:36 UTC, 0xAlcibiades commented on examples/typescript/gen/valorem/trade/v1/auth_pb.ts
This generated file should not be in version control

2023-06-24 21:36 UTC, 0xAlcibiades commented on examples/typescript/gen/valorem/trade/v1/auth_connect.ts
This generated file should not be in version control

2023-06-24 21:36 UTC, 0xAlcibiades commented on examples/typescript/src/RFQ_maker.ts
Looks good.

2023-06-24 21:36 UTC, 0xAlcibiades commented on examples/typescript/src/RFQ_taker.ts
Looks good.

2023-06-24 22:53 UTC, 0xAlcibiades approved these changes

2023-06-24 22:53 UTC, merged